#pragma once
// ============================================================================
// [BUILD FINGERPRINT] Auto-generated by generate_build_info.ps1 -- do not
// hand-edit; re-run the script to refresh this value before compiling if you
// want GIT_COMMIT_HASH to reflect the commit actually being built.
//
// This checked-in default is "UNKNOWN" so that a fresh clone -- or any build
// where the script was never run -- still compiles and reports its identity
// honestly, instead of silently keeping a stale or fabricated hash. See
// BUILD_FINGERPRINT.md for the full design.
//
// A "-dirty" suffix means the working tree had uncommitted changes (tracked
// or untracked) at generation time -- the hash itself is still the real,
// unmodified short commit hash; "-dirty" is only ever an appended flag, never
// a fabricated value.
// ============================================================================
#define GIT_COMMIT_HASH "e690765"
