# ============================================================================
# [BUILD FINGERPRINT] generate_build_info.ps1
# ============================================================================
# Regenerates build_info.h with the current short Git commit hash, plus a
# dirty-tree indicator.
#
# [v16.5-autohook] Wired into an automatic pre-build hook (see
# platform.local.txt in the installed esp32 core + BUILD_FINGERPRINT.md,
# section "Build system changes") -- this script now runs on every compile,
# from both Arduino IDE and arduino-cli, with no manual step required.
# Running it by hand is still safe/harmless if you want to inspect the
# result ahead of time.
#
# Never fabricates a hash: if git is unavailable, this directory is not a
# git repository, or the commit lookup fails for any reason, writes
# "UNKNOWN" instead of any placeholder-looking value -- that is a legitimate
# successful outcome, not an error. Dirty-tree detection only ever APPENDS
# "-dirty" to a real, resolved hash -- it never runs (and never matters)
# when the hash itself is "UNKNOWN".
#
# Dirty check: `git status --porcelain` against the WHOLE repository (not
# just this sketch folder), matching how "is HEAD what's actually built"
# should be interpreted -- and deliberately including untracked files, since
# Arduino compiles every .ino/.h/.cpp sitting in this folder whether or not
# it is tracked by git.
#
# Fail-fast contract (requirement: "fail the build if build_info.h cannot be
# regenerated"): the only allowed *successful* outcomes are a resolved hash
# (clean or -dirty) or the honest "UNKNOWN" fallback when git itself is
# unavailable. Anything else -- the header can't be written, the script
# can't find its own directory, an unexpected exception -- exits non-zero so
# the pre-build hook aborts compilation instead of silently compiling with a
# stale or missing header.
# ============================================================================

$ErrorActionPreference = 'Stop'

try {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    if (-not $scriptDir -or -not (Test-Path $scriptDir)) {
        throw "Could not resolve script directory from `$MyInvocation."
    }
    $headerPath = Join-Path $scriptDir "build_info.h"

    $hash  = "UNKNOWN"
    $dirty = $false

    try {
        $result = git -C $scriptDir rev-parse --short=7 HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $result) {
            $hash = $result.Trim()

            $statusResult = git -C $scriptDir status --porcelain 2>$null
            if ($LASTEXITCODE -eq 0 -and $statusResult) {
                $dirty = $true
            }
        }
    } catch {
        # git missing/unavailable is a legitimate, honest "UNKNOWN" -- not a failure.
        $hash  = "UNKNOWN"
        $dirty = $false
    }

    $hashForHeader = $hash
    if ($hash -ne "UNKNOWN" -and $dirty) {
        $hashForHeader = "$hash-dirty"
    }

    $lines = @(
        '#pragma once',
        '// ============================================================================',
        '// [BUILD FINGERPRINT] Auto-generated by generate_build_info.ps1 -- do not',
        '// hand-edit. Regenerated automatically on every compile by a pre-build hook',
        '// (see platform.local.txt in the installed esp32 core); running it by hand',
        '// is unnecessary but harmless.',
        '//',
        '// This checked-in default is "UNKNOWN" so that a fresh clone -- or any build',
        '// where the hook could not run -- still compiles and reports its identity',
        '// honestly, instead of silently keeping a stale or fabricated hash. See',
        '// BUILD_FINGERPRINT.md for the full design.',
        '//',
        '// A "-dirty" suffix means the working tree had uncommitted changes (tracked',
        '// or untracked) at generation time -- the hash itself is still the real,',
        '// unmodified short commit hash; "-dirty" is only ever an appended flag, never',
        '// a fabricated value.',
        '// ============================================================================',
        "#define GIT_COMMIT_HASH `"$hashForHeader`""
    )

    Set-Content -Path $headerPath -Value $lines -Encoding utf8 -ErrorAction Stop

    # Verify the write actually landed -- catches silent no-ops (e.g. ACL/locking
    # quirks that don't throw) that would otherwise leave a stale header in place.
    $writtenBack = Get-Content -Path $headerPath -Raw -ErrorAction Stop
    if ($writtenBack -notmatch [regex]::Escape("GIT_COMMIT_HASH `"$hashForHeader`"")) {
        throw "Post-write verification failed: $headerPath does not contain the expected GIT_COMMIT_HASH value."
    }

    if ($hash -eq "UNKNOWN") {
        Write-Output "[generate_build_info] GIT_COMMIT_HASH = UNKNOWN -> $headerPath"
    } elseif ($dirty) {
        Write-Output "[generate_build_info] GIT_COMMIT_HASH = $hash (DIRTY working tree) -> $headerPath"
    } else {
        Write-Output "[generate_build_info] GIT_COMMIT_HASH = $hash (clean) -> $headerPath"
    }
    exit 0
} catch {
    Write-Error "[generate_build_info] FAILED to regenerate build_info.h -- $($_.Exception.Message)"
    exit 1
}
