# ============================================================================
# [BUILD FINGERPRINT] generate_build_info.ps1
# ============================================================================
# Regenerates build_info.h with the current short Git commit hash, plus a
# dirty-tree indicator.
#
# Run this BEFORE compiling if you want the firmware's GIT_COMMIT_HASH (and
# therefore its BUILD_ID) to reflect the commit actually being built.
# Arduino IDE / arduino-cli has no native git-integration hook, so this is a
# manual (or CI-wired) pre-build step -- see BUILD_FINGERPRINT.md, section
# "Build system changes", for why this exists and how to wire it into an
# automated build if desired.
#
# Never fabricates a hash: if git is unavailable, this directory is not a
# git repository, or the command fails for any reason, writes "UNKNOWN"
# instead of any placeholder-looking value. Dirty-tree detection only ever
# APPENDS "-dirty" to a real, resolved hash -- it never runs (and never
# matters) when the hash itself is "UNKNOWN".
#
# Dirty check: `git status --porcelain` against the WHOLE repository (not
# just this sketch folder), matching how "is HEAD what's actually built"
# should be interpreted -- and deliberately including untracked files, since
# Arduino compiles every .ino/.h/.cpp sitting in this folder whether or not
# it is tracked by git.
# ============================================================================

$scriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$headerPath = Join-Path $scriptDir "build_info.h"

$hash  = "UNKNOWN"
$dirty = $false

try {
    $result = git -C $scriptDir rev-parse --short=7 HEAD 2>$null
    if ($LASTEXITCODE -eq 0 -and $result) {
        $hash = $result.Trim()

        $statusResult = git -C $scriptDir status --porcelain 2>$null
        if ($LASTEXITCODE -eq 0 -and $statusResult) {
            $dirty = $true
        }
    }
} catch {
    $hash  = "UNKNOWN"
    $dirty = $false
}

$hashForHeader = $hash
if ($hash -ne "UNKNOWN" -and $dirty) {
    $hashForHeader = "$hash-dirty"
}

$lines = @(
    '#pragma once',
    '// ============================================================================',
    '// [BUILD FINGERPRINT] Auto-generated by generate_build_info.ps1 -- do not',
    '// hand-edit; re-run the script to refresh this value before compiling if you',
    '// want GIT_COMMIT_HASH to reflect the commit actually being built.',
    '//',
    '// This checked-in default is "UNKNOWN" so that a fresh clone -- or any build',
    '// where the script was never run -- still compiles and reports its identity',
    '// honestly, instead of silently keeping a stale or fabricated hash. See',
    '// BUILD_FINGERPRINT.md for the full design.',
    '//',
    '// A "-dirty" suffix means the working tree had uncommitted changes (tracked',
    '// or untracked) at generation time -- the hash itself is still the real,',
    '// unmodified short commit hash; "-dirty" is only ever an appended flag, never',
    '// a fabricated value.',
    '// ============================================================================',
    "#define GIT_COMMIT_HASH `"$hashForHeader`""
)

Set-Content -Path $headerPath -Value $lines -Encoding utf8

if ($hash -eq "UNKNOWN") {
    Write-Output "[generate_build_info] GIT_COMMIT_HASH = UNKNOWN -> $headerPath"
} elseif ($dirty) {
    Write-Output "[generate_build_info] GIT_COMMIT_HASH = $hash (DIRTY working tree) -> $headerPath"
} else {
    Write-Output "[generate_build_info] GIT_COMMIT_HASH = $hash (clean) -> $headerPath"
}
